In [1]:
import math

def basic_sigmoid_function(X):
  s = 1 / (1+ math.exp(-X))
  return s

In [2]:
print(basic_sigmoid_function(-1))

0.2689414213699951


In [3]:
import numpy as np

z = np.array([1,2,3])
print(np.exp(z))

[ 2.71828183  7.3890561  20.08553692]


In [4]:
print(z + 3)

[4 5 6]


In [5]:
def sigmoid_function(z):
  e = 1 / (1 + np.exp(-z))
  return e

print(sigmoid_function(z))

[0.73105858 0.88079708 0.95257413]


In [6]:
def gradient_sigmoid_derrivative(z):
  sd = sigmoid_function(z) * (1- sigmoid_function(z))
  return sd
print(gradient_sigmoid_derrivative(z))

[0.19661193 0.10499359 0.04517666]


In [7]:
def image_2_vector(images):
  x = images.reshape(images.shape[0]*images.shape[1] * images.shape[2],1)
  return x

In [8]:
images = np.array([[[ 0.67826139, 0.29380381],
            [ 0.90714982, 0.52835647],
            [ 0.4215251, 0.45017551]],

            [[ 0.92814219, 0.96677647],
            [ 0.85304703, 0.52351845],
            [0.19981397, 0.27417313]],

            [[ 0.60659855, 0.00533165],
            [ 0.10820313, 0.49978937],
            [0.34144279, 0.94630077]]])
print(str(image_2_vector(images)))

[[0.67826139]
 [0.29380381]
 [0.90714982]
 [0.52835647]
 [0.4215251 ]
 [0.45017551]
 [0.92814219]
 [0.96677647]
 [0.85304703]
 [0.52351845]
 [0.19981397]
 [0.27417313]
 [0.60659855]
 [0.00533165]
 [0.10820313]
 [0.49978937]
 [0.34144279]
 [0.94630077]]


In [9]:
def normilization_Rows(a):
  a_normilize = np.linalg.norm(a,axis = 1 , keepdims = True)
  a = a/a_normilize
  return a

In [10]:
a = np.array([[0,1000,4],[2,6,4]])
print(str(normilization_Rows(a)))

[[0.         0.999992   0.00399997]
 [0.26726124 0.80178373 0.53452248]]


In [11]:
def softmax_function(x):
  exp_x = np.exp(x)
  x_sum = np.sum(exp_x , axis = 1 , keepdims = True)
  v = exp_x / x_sum
  return v

In [12]:
x = np.array([
    [6, 4, 9, 6, 5],
    [9, 8, 4, 0 ,3]])
print(str(softmax_function(x)))

[[4.42698214e-02 5.99126881e-03 8.89183131e-01 4.42698214e-02
  1.62859571e-02]
 [7.26100642e-01 2.67117499e-01 4.89242764e-03 8.96079380e-05
  1.79982355e-03]]


In [13]:
import time

x1 = [9, 2, 5, 0, 0, 7, 5, 0, 0, 0, 9, 2, 5, 0, 0]
x2 = [9, 2, 2, 9, 0, 9, 2, 5, 0, 0, 9, 2, 5, 0, 0]

tic = time.process_time()
dot = 0
for i in range(len(x1)):
    dot+= x1[i]*x2[i]
toc = time.process_time()
print(str(dot)+"\n"+ str(1000*(toc-tic))+"ms")

# VECTORIZED DOT IMPLEMENTATION
tic = time.process_time()
outer = np.zeros((len(x1),len(x2)))
for i in range(len(x1)):
    for j in range(len(x2)):
        outer[i,j] = x1[i]*x2[j]
toc = time.process_time()
print(str(outer)+"\n"+ str(1000*(toc-tic))+"ms")

278
0.19679999999988596ms
[[81. 18. 18. 81.  0. 81. 18. 45.  0.  0. 81. 18. 45.  0.  0.]
 [18.  4.  4. 18.  0. 18.  4. 10.  0.  0. 18.  4. 10.  0.  0.]
 [45. 10. 10. 45.  0. 45. 10. 25.  0.  0. 45. 10. 25.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [63. 14. 14. 63.  0. 63. 14. 35.  0.  0. 63. 14. 35.  0.  0.]
 [45. 10. 10. 45.  0. 45. 10. 25.  0.  0. 45. 10. 25.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [81. 18. 18. 81.  0. 81. 18. 45.  0.  0. 81. 18. 45.  0.  0.]
 [18.  4.  4. 18.  0. 18.  4. 10.  0.  0. 18.  4. 10.  0.  0.]
 [45. 10. 10. 45.  0. 45. 10. 25.  0.  0. 45. 10. 25.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]
0.4337799999998282ms


In [21]:
x1 = np.random.rand(10000)
x2 = np.random.rand(10000)

tic = time.process_time()
dot = 0
for i in range(len(x1)):
  dot+= x1[i]*x2[i]
toc = time.process_time()
print("dot = " +str(dot)+"\n -----computation Time --------" + str(1000*(toc-tic)) +"ms")

dot = 2485.793146233248
 -----computation Time --------8.937783000000366ms


In [20]:
tic = time.process_time()
dot = np.dot(x1,x2)
toc = time.process_time()
print("dot = " +str(dot)+"\n -----computation Time --------" + str(1000*(toc-tic)) +"ms")

dot = 2515.742811616814
 -----computation Time --------0.1793670000003189ms
